spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

# ?????????, ????? ??????? ????????? ?? ?????????
spring.profiles.active=local

# ????? ????? (??? ?????????? ?? ?????? .env ??? ?????????? ???????)
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
jwt_secret=${JWT_SECRET}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}