spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

# ?????????, ????? ??????? ????????? ?? ?????????
spring.profiles.active=local

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.miniapp.url=${TELEGRAM_MINIAPP_URL}
jwt_secret=${JWT_SECRET}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.cache.type=redis

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
