spring.application.name=backend

telegram.bot.token=8753066412:AAFKR6kNxIBa1eZbxQEtIAYM4T43Mqc3gyw

spring.datasource.url=jdbc:postgresql://localhost:5432/matchmaking_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate ??? ??????? ??????? users ??? ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt_secret=1e4acd3cd2cd5944c4f08328a9e3ae1aacc44d233546b007909543ecf38f35b7