# ???? ?????? ???? ????????? ???????
spring.jpa.hibernate.ddl-auto=update

# ??????? SQL-??????? ? ???????
spring.jpa.show-sql=true

# ????????? ??????? ?????? ?????? (??????, ????? ???????? ??????? ?? localhost)
app.cors.allowed-origin=*